"""Compile clip performance into a knowledge-base file Claude reads when
picking shorts. Structured (no LLM): regenerated whenever metrics sync.

The clip-picking skills glob .podcli/knowledge/*.md, so writing the digest
here is what closes the loop — the next suggest_clips run is informed by what
actually performed.
"""
from __future__ import annotations

import os
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Callable, Optional

from config.paths import paths
from services.clips_history import load_clips_history

LEARNINGS_FILE = "13-performance-learnings.md"


def _has_perf(c: dict) -> bool:
    m = c.get("metrics") or {}
    return m.get("views") is not None or m.get("retention") is not None


def _agg(clips: list[dict], key: Callable[[dict], Any]) -> list[dict]:
    groups: dict[str, list[dict]] = defaultdict(list)
    for c in clips:
        groups[key(c) or "—"].append(c)
    out = []
    for k, cs in groups.items():
        vals = lambda f: [c["metrics"][f] for c in cs if (c.get("metrics") or {}).get(f) is not None]
        ret, ctr, views = vals("retention"), vals("ctr"), vals("views")
        out.append({
            "key": k, "n": len(cs),
            "ret": round(sum(ret) / len(ret), 1) if ret else None,
            "ctr": round(sum(ctr) / len(ctr), 1) if ctr else None,
            "views": int(sum(views) / len(views)) if views else None,
        })
    return out


def _length_bucket(c: dict) -> str:
    d = c.get("duration") or 0
    return "<25s" if d < 25 else "25-35s" if d < 35 else "35-45s" if d < 45 else "45s+"


def write_learnings(min_clips: int = 3) -> Optional[str]:
    """Regenerate the performance-learnings knowledge file. None if too little data."""
    clips = [c for c in load_clips_history() if _has_perf(c)]
    if len(clips) < min_clips:
        return None

    by_type = sorted(_agg(clips, lambda c: c.get("content_type")), key=lambda r: r["ret"] or 0, reverse=True)
    by_caption = sorted(_agg(clips, lambda c: c.get("caption_style")), key=lambda r: r["ctr"] or 0, reverse=True)
    by_length = sorted(_agg(clips, _length_bucket), key=lambda r: r["ret"] or 0, reverse=True)
    top = sorted(clips, key=lambda c: (c.get("metrics") or {}).get("views") or 0, reverse=True)[:5]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    L: list[str] = [
        "# Performance learnings",
        "",
        "<!-- AUTO-GENERATED by `podcli youtube sync`. The 'What's working now' section is",
        "     regenerated each sync — edits there are overwritten. -->",
        "",
        f"## What's working now (updated {now} · {len(clips)} published clips)",
        "",
        "Retention = content quality (did it hold viewers). CTR = packaging (title/thumbnail). Views = reach.",
        "",
        "**By moment type — retention:**",
    ]
    L += [f"- {r['key']}: {r['ret']}% retention · {r['ctr']}% CTR · ~{r['views']} views (n={r['n']})" for r in by_type]
    L += ["", "**By caption style — CTR:**"]
    L += [f"- {r['key']}: {r['ctr']}% CTR · {r['ret']}% retention (n={r['n']})" for r in by_caption]
    L += ["", "**By length — retention:**"]
    L += [f"- {r['key']}: {r['ret']}% retention (n={r['n']})" for r in by_length]
    L += ["", "**Top performers:**"]
    L += [f"- \"{c['title']}\" — {(c.get('metrics') or {}).get('views')} views, {(c.get('metrics') or {}).get('retention')}% retention [{c.get('content_type', '?')}]" for c in top]
    L += ["", "## Guidance for picking shorts", ""]
    if by_type:
        L.append(f"- Prioritize **{by_type[0]['key']}** moments — highest retention ({by_type[0]['ret']}%).")
    best_ctr = next((r for r in by_caption if r["ctr"]), None)
    if best_ctr:
        L.append(f"- **{best_ctr['key']}** captions earn the most clicks ({best_ctr['ctr']}% CTR).")
    if by_length:
        L.append(f"- Target **{by_length[0]['key']}** clips for retention.")
    L.append("")

    os.makedirs(paths["knowledge"], exist_ok=True)
    path = os.path.join(paths["knowledge"], LEARNINGS_FILE)
    with open(path, "w") as f:
        f.write("\n".join(L))
    return path
